-- MySQL Script generated by MySQL Workbench
-- Wed Oct 23 17:52:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema labdb0_0_4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema labdb0_0_4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `labdb0_0_4` DEFAULT CHARACTER SET utf8 ;
USE `labdb0_0_4` ;

-- -----------------------------------------------------
-- Table `labdb0_0_4`.`laboratory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labdb0_0_4`.`laboratory` (
  `id` INT(4) ZEROFILL NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT 'unnamed laboratory',
  `manager_email` VARCHAR(45) NULL DEFAULT 'unspecified',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labdb0_0_4`.`reagent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labdb0_0_4`.`reagent` (
  `id` INT(8) ZEROFILL NOT NULL AUTO_INCREMENT,
  `lab_id` INT(4) ZEROFILL NOT NULL,
  `name_common` VARCHAR(45) NULL DEFAULT 'unnamed reagent',
  `formula` VARCHAR(45) NULL DEFAULT 'not set',
  `CAS` VARCHAR(45) NULL DEFAULT 'not set',
  `locations` VARCHAR(45) NULL DEFAULT 'Ask my boss!',
  `private` TINYINT NULL DEFAULT 0,
  `secure` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `lab_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_reagent_laboratory_idx` (`lab_id` ASC),
  UNIQUE INDEX `CAS_UNIQUE` (`CAS` ASC),
  CONSTRAINT `fk_reagent_laboratory`
    FOREIGN KEY (`lab_id`)
    REFERENCES `labdb0_0_4`.`laboratory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `labdb0_0_4` ;

-- -----------------------------------------------------
-- Placeholder table for view `labdb0_0_4`.`user_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labdb0_0_4`.`user_view` (`id` INT, `lab_id` INT, `name_common` INT, `formula` INT, `CAS` INT, `locations` INT, `private` INT, `secure` INT);

-- -----------------------------------------------------
-- Placeholder table for view `labdb0_0_4`.`private_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labdb0_0_4`.`private_view` (`id` INT, `lab_id` INT, `name_common` INT, `formula` INT, `CAS` INT, `private` INT, `secure` INT);

-- -----------------------------------------------------
-- View `labdb0_0_4`.`user_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labdb0_0_4`.`user_view`;
USE `labdb0_0_4`;
CREATE OR REPLACE VIEW `user_view` AS SELECT * FROM `reagent` WHERE secure = 0;

-- -----------------------------------------------------
-- View `labdb0_0_4`.`private_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labdb0_0_4`.`private_view`;
USE `labdb0_0_4`;
CREATE  OR REPLACE VIEW `private_view` AS SELECT id, lab_id, name_common, formula, CAS, private, secure FROM `reagent`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
