-- MySQL Script generated by MySQL Workbench
-- Mon Dec  9 11:59:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema labdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `labdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `labdb` ;

-- -----------------------------------------------------
-- Table `labdb`.`lab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labdb`.`lab` (
  `id` INT(16) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL DEFAULT 'unnamed laboratory',
  `manager` VARCHAR(45) DEFAULT 'unspecified',
  `manager_email` VARCHAR(45) DEFAULT 'unspecified',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `labdb`.`reagent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labdb`.`reagent` (
  `id` INT(8) NOT NULL AUTO_INCREMENT,
  `lab_id` INT(16) NOT NULL,
  `name` VARCHAR(45) DEFAULT 'unnamed reagent',
  `formula` VARCHAR(45) DEFAULT 'not set',
  `CAS` VARCHAR(45) DEFAULT 'not set',
  `location` VARCHAR(45) DEFAULT 'Ask my boss!',
  `private` TINYINT(4) DEFAULT '0',
  `secure` TINYINT(4) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `CAS_UNIQUE` (`CAS` ASC) ,
  INDEX `fk_reagent_laboratory_idx` (`lab_id` ASC) ,
  CONSTRAINT `fk_reagent_laboratory`
    FOREIGN KEY (`lab_id`)
    REFERENCES `labdb`.`lab` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `labdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labdb`.`user` (
  `id` INT(32) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL,
  `passwd` VARCHAR(256) NOT NULL,
  `role` ENUM('user', 'admin') NOT NULL DEFAULT 'user',
  `lang` ENUM('en', 'es') NOT NULL DEFAULT 'en',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `labdb`.`member_of`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labdb`.`member_of` (
  `user_id` INT(32) NOT NULL,
  `lab_id` INT(16) NOT NULL,
  PRIMARY KEY (`user_id`, `lab_id`),
  INDEX `fk_user_has_laboratory_laboratory1_idx` (`lab_id` ASC) ,
  INDEX `fk_user_has_laboratory_user1_idx` (`user_id` ASC) ,
  UNIQUE INDEX `laboratory_id_UNIQUE` (`lab_id` ASC) ,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) ,
  CONSTRAINT `fk_user_has_laboratory_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `labdb`.`user` (`id`),
  CONSTRAINT `fk_user_has_laboratory_laboratory1`
    FOREIGN KEY (`lab_id`)
    REFERENCES `labdb`.`lab` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `labdb`.`history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labdb`.`history` (
  `search_id` INT(64) NOT NULL AUTO_INCREMENT,
  `user_id` INT(32) NOT NULL,
  `search` VARCHAR(128) NULL DEFAULT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_history_user1_idx` (`user_id` ASC) ,
  PRIMARY KEY (`search_id`),
  CONSTRAINT `fk_history_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `labdb`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
